export { default as LoadingModal} from '~/modals/LoadingModal'
export { default as LocationModal} from '~/modals/LocationModal'
export { default as VericationEmailModal} from '~/modals/VericationEmailModal'
export { default as SuccessModal} from '~/modals/SuccessModal'
export { default as ModalizeSelect} from '~/modals/ModalizeSelect'